apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sleep
  namespace: default
spec:
  workloadSelector:
    labels:
      app: sleep
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
  - port:
      number: 80
      protocol: HTTP
      name: frontend
    hosts:
    - "./*"
