apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v2.3
  template:
    metadata:
      labels:
        app: frontend
        version: v2.3
    spec:
      containers:
        - env:
          - name: BACKEND_URL
            value: 'http://demoapp:8080'
          - name: PORT
            value: '80'
          image: ikubernetes/frontend:v2.3.1
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
---
