---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
    version: v2.1
  name: demoapp
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
      version: v2.1
  template:
    metadata:
      labels:
        app: demoapp
        version: v2.1
    spec:
      containers:
      - image: ikubernetes/demoapp:v2.1
        imagePullPolicy: IfNotPresent
        name: demoapp
        env:
        - name: "PORT"
          value: "8080"
        - name: "VERSION"
          value: "v2.1"
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demoapp
  type: ClusterIP
---
