apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-tracing-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100.00
