# 禁用 demoapp 服务的访问日志
#
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-demoapp-logging
  namespace: default
spec:
  selector:
    matchLabels:
      app: demoapp
  accessLogging:
  - providers:
    - name: otel
    disabled: true
