apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demoapp
spec:
  hosts:
  - demoapp
  http:
  - name: canary
    match:
    - headers:
        x-canary:
          exact: "true"
    route:
    - destination:
        host: demoapp
        subset: v2-canary
      headers:
        request:
          set:
            User-Agent: wget
        response:
          add:
            x-canary: "true"
    fault:
      abort:
        percentage:
          value: 20
        httpStatus: 555
  - name: default
    route:
    - destination:
        host: demoapp
        subset: v2
    fault:
      delay:
        percentage:
          value: 20
        fixedDelay: 5s
