version: '3.3'

services:
  nginx2501:
    image: nginx:1.25-alpine
    volumes:
      - ./html/nginx2501:/usr/share/nginx/html/
    networks:
      nginx_net:
        ipv4_address: 172.31.201.11
        aliases:
        - nginx
    expose:
      - "80"
    ports:
      - "172.29.1.201:8091:80"

  nginx2502:
    image: nginx:1.25-alpine
    volumes:
      - ./html/nginx2502:/usr/share/nginx/html/
    networks:
      nginx_net:
        ipv4_address: 172.31.201.12
        aliases:
        - nginx
    expose:
      - "80"
    ports:
      - "172.29.1.202:8091:80"

  nginx2601:
    image: nginx:1.26-alpine
    volumes:
      - ./html/nginx2601:/usr/share/nginx/html/
    networks:
      nginx_net:
        ipv4_address: 172.31.201.13
        aliases:
        - nginx
        - canary
    expose:
      - "80"
    ports:
      - "172.29.1.203:8091:80"

networks:
  nginx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.201.0/24
