# Author: MageEdu <mage@magedu.com>
# Site: www.magedu.com
#
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demoapp
spec:
  host: demoapp
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
  - name: v2
    labels:
      version: v2.1
    trafficPolicy:
      loadBalancer:
        consistentHash:
          httpHeaderName: x-user
  - name: v2-canary
    labels:
      version: v2.1-canary
